language: node_js
node_js:
  - 0.8
install: npm install ; npm run-script install-dev
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - "cake build"
#script: "cake test[all]"
