language: node_js
node_js:
  - 0.4
  - 0.6
install: npm install ; npm install mongodb
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - "cake build"
#script: "cake test[all]"
