language: node_js
node_js:
  - 0.8
install: npm install
services: mongodb
# @todo once `make test-client` is working
before_script:
  - "npm install grunt"
  - "make setup-test-client"
  - "make start-test-client &"
  - sleep 3
#  - "cd test/example"
#  - "grunt --config ./grunt.coffee"
#  - "cd ../.."
#  - "node test/example -p 3210"
#  - sleep 3 # give Web server some time to bind to sockets, etc